apiVersion: v1
kind: Service
metadata:
  name: osm-server-service
  labels:
    {{- include "anything-finder.labels" . | nindent 4 }}
    app.kubernetes.io/component: osm-server
spec:
  selector:
    app.kubernetes.io/component: osm-server
  ports:
    - name: http
      port: {{ .Values.osm.service.port }}
      targetPort: 80
