{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    {{- include "anything-finder.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
stringData:
  postgres-password: {{ .Values.postgres.password | quote }}
  dsn: {{ printf "postgresql://%s:%s@postgres-service:%v/%s" .Values.postgres.user .Values.postgres.password .Values.postgres.service.port .Values.postgres.database | quote }}
{{- end }}
